name: deploy module
on:
  push:
    branches: [main]

jobs:
  update-deps:
    name: Update node module
    runs-on: ubuntu-latest
    env:
      CI: true
      SNCF_TOKEN: ${{ secrets.SNCF_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: download deps
        run: npm ci
      - name: test run
        run: npm test
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
