name: Publish SNCF.JS website to GitHub
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - prepare/V2

jobs:
  publish:
    name: Publish to the retype branch

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: download deps
        run: npm ci

      - name: Update docs date and author data
        run: npm run update_doc_data

      - uses: retypeapp/action-build@latest

      - uses: retypeapp/action-github-pages@latest
        with:
          branch: dist
          update-branch: true
