name: Test module
on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
jobs:
  npm:
    name: npm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install node.js v16
        uses: actions/setup-node@v2
        
      - name: Run test
      - run: npm test
      
