# .github/workflows/publish.yml
name: Generate the documentation and push to dist branch

on:
  push:
    branches:
      - prepare/V2

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: git-checkout
        uses: actions/checkout@v2

      - name: Build
        uses: retypeapp/action-build@latest
    
      - name: Push
        uses: retypeapp/action-github-pages@latest
        with:
          update-branch: true
