name: test module
on:
  push:
    branches-ignore:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CI: true
      SNCF_TOKEN: ${{ secrets.SNCF_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: download deps
        run: npm ci
      - name: test run
        run: npm test
